### ISSUE TITLE
Training data in fasta format?

### ISSUE THREAD

**Issue by beef-broccoli** [psipred/DeepCov#2]
Hello,

Do you guys have the training data in FASTA format? Or is there a way I can convert the provided PSICOV-format data to FASTA? Thank you 

Best,
Jason

**Comment by shaunmk** [comment]
Hi,
The PSICOV-formatted alignments can be converted to FASTA format by just inserting dummy sequence identifiers before each sequence. You can use something like:
 `awk 'BEGIN {count=1} {printf (">%s_%d\n", "seq", count); print; count++}' target.aln > target.afa `

**Comment by beef-broccoli** [comment]
Thank you for the reply. Yes dummy sequence identifiers probably work, but it will be much better to have PDB IDs for all the sequences. Is there a list somewhere with all the PDB IDs?

**Comment by shaunmk** [comment]
We didn't retain the true sequence identifiers for this set. The sequences in each alignment were retrieved from an HHblits database (uniprot20 at the time), so they would be UniProt IDs rather than PDB identifiers.

As for the PDB identifiers for each training example (the source of the query sequence used to make each alignment), these are in their filenames. For example 12asA0 is to be parsed as: PDB ID 12AS, chain A, domain 0.

**Comment by beef-broccoli** [comment]
Thanks for the help!
